# ==========================================
# FILE: server.py
# PURPOSE: Connects Redis Scraped Data to Sensio UI
# ==========================================

from flask import Flask, jsonify
from flask_cors import CORS
import redis
import json

app = Flask(__name__)
CORS(app) # Allows index.html and tenders.html to safely pull data locally

# Connect to your active scraping Redis instance
r = redis.Redis(host="localhost", port=6379, db=0, decode_responses=True)

@app.route('/api/sensio-stream', methods=['GET'])
def stream_sensio_data():
    tenders_pool = []
    
    # Scan keys generated by your Playwright loops
    for key in r.scan_iter("tender:*"):
        if r.type(key) == "string":
            raw_val = r.get(key)
            if not raw_val:
                continue
                
            raw = json.loads(raw_val)
            
            # Map Python Scraper fields -> Your exact Sensio Data Properties
            normalized_tender = {
                "id": raw.get("Primary Key", "N/A"),
                "title": raw.get("Tender Title", "Untitled Tender"),
                "category": str(raw.get("Sector", "health")).lower(), # Sensio handles lowercase filter keys
                "country": raw.get("Country", "Global"),
                "openingDate": raw.get("Opening Date", "N/A"),
                "closingDate": raw.get("Expiry Date", "N/A"),
                "relevancyScore": float(raw.get("Relevancy Score", 0.50)),
                "budgetINR": int(raw.get("Budget in INR Maximum", 0)),
                "description": raw.get("Tender Description", "No description structural content parsed."),
                "eligibility": f"Authority: {raw.get('Organisation Name', 'Unknown')}. Estimated timeline calculation: {raw.get('Timeline', 0)} days.",
                "link": raw.get("Link to the Tender", "https://google.com")
            }
            tenders_pool.append(normalized_tender)

    # Wrap the output matching your custom storage schema layout
    return jsonify({
        "sourceFile": "Live Local Playwright Redis Pipeline",
        "tenders": tenders_pool
    })

if __name__ == '__main__':
    print("🚀 Sensio UI Data Server Online on http://localhost:5000")
    app.run(host="0.0.0.0", port=5000, debug=False)